spring:
  datasource:
    username: root
    password: yz941029
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-aliases-package: com.yang.pojo
  mapper-locations: classpath:mybatis/*.xml